### ISSUE TITLE
How to start Android Studio?

### ISSUE THREAD

**Issue by oliverkarst** [samtstern/android-vagrant#31]
Sorry for asking this stupid question and this is really not an issue, but I am fairly new to vagrant and docker, and I do not know how can I start Android Studio in the docker container with X-Windows?

Would it be possible to extend to the README.md with a little peace of command-line how to start Android Studio at the end?
That would be great :-)

Thanks so much

**Comment by samtstern** [comment]
It should start automatically when you run the android studio Docker image.  Closing this issue because this repo is no longer supported, so if it's broken it unfortunately will stay broken.
