### ISSUE TITLE
When Error updating SDK components when running android studio for first time

### ISSUE THREAD

**Issue by arojoal** [samtstern/android-vagrant#32]
I have run run_docker.sh "samtstern/android-studio" and it starts updating SDK and show an Error: 

Refresh Sources:
  Fetched Add-ons List successfully
  Refresh Sources

Installing Archives:
  Preparing to install archives
  URL not found: /usr/local/android-sdk-linux/temp/tools_r24.3.4-linux.zip (Permission denied)
  Done. Nothing was installed.
The following SDK component was not installed: tools

**Comment by samtstern** [comment]
Sorry @arojoal this repo is no longer actively supported.  It was an experiment.  Closing this issue.
